//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackerrank_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Job_id { get; set; }
        public string CustomerName { get; set; }
        public string Location { get; set; }
        public string TechniciansAssigned { get; set; }
        public decimal Estimate { get; set; }
    }
}
